# Generated by Django 3.1.7 on 2022-11-11 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('course', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='uva_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=200)),
                ('instructor_email', models.CharField(max_length=200)),
                ('course_number', models.IntegerField()),
                ('semester_code', models.IntegerField()),
                ('course_section', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('catalog_number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=200)),
                ('class_capacity', models.IntegerField()),
                ('wait_list', models.IntegerField()),
                ('wait_cap', models.IntegerField()),
                ('enrollment_total', models.IntegerField()),
                ('enrollment_available', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('facility_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='uva_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_1', to=settings.AUTH_USER_MODEL)),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='friendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
